### ISSUE TITLE
strings with dots (..) converted to urls

### ISSUE THREAD

**Issue by milmaj** [liip/LiipUrlAutoConverterBundle#21]
Normal Strings like

-gf..gf..
-xx..xx..xx
-a..bb......

are converted to urls.

Example:
a..bb.
is converted to
<a class="" target="_blank" href="http://a..bb.....">a..bb.....</a>.
(The last point not including in the link)

**Comment by feng-di** [comment]
positionner....des
positionner...des
positionner..des
positionner..des..

all of the strings above will  be converted to links, will this issue be fixed?

**Comment by sagikazarmark** [comment]
I think using twitter's text conformance would help a lot:

https://github.com/twitter/twitter-text/blob/master/conformance/autolink.yml

There are already existing libraries for this, unsure about stability, but I think those are still better.

**Comment by lsmith77** [comment]
@sagikazarmark sounds good to me .. in general like I said in the other ticket I want to move to a solid library .. but I kind of lack the time to work on this .. but I am totally open to a PR.

**Comment by CaptainStiggz** [comment]
@lsmith77 I'm no regex expert, but if you need a quick fix to the ellipsis issue, you can try this. Either overwrite the original regex used in the Liip bundle (not recommended) or register your own Twig filter, and copy most of their logic, with a slight adjustment to the regex used. For more information on custom Twig filters for Symfony: http://symfony.com/doc/current/cookbook/templating/twig_extension.html

```php
public function getFilters()
{
    return array(
        new \Twig_SimpleFilter(
            'myurlfilter',
            array($this, 'autoConvertUrls'),
            array(
                'pre_escape' => 'html',
                'is_safe' => array('html'),
            )
        )
    );
}

public function autoConvertUrls($string)
{
    //original
    //$pattern = '/(href="|src=")?([-a-zA-Zа-яёА-ЯЁ0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-zа-яё]{2,4}\b(\/?[-\p{L}0-9@:%_\+.~#?&\/\/=\(\),]*)?)/u';
    
    //adjusted
    $pattern = '/(href="|src=")?(([-a-zA-Zа-яёА-ЯЁ0-9@:%_\+~#?&\/\/=]{2,256}\.){1,256}[a-zа-яё]{2,4}\b(\/?[-\p{L}0-9@:%_\+.~#?&\/\/=\(\),]*)?)/u';
    
    $stringFiltered = preg_replace_callback($pattern, array($this, 'callbackReplace'), $string);
    return $stringFiltered;
}

public function callbackReplace($matches)
{
    if ($matches[1] !== '') {
        return $matches[0]; // don't modify existing <a href="">links</a> and <img src="">
    }
    $url = $matches[2];
    $urlWithPrefix = $matches[2];
    if (strpos($url, '@') !== false) {
        $urlWithPrefix = 'mailto:'.$url;
    } elseif (strpos($url, 'https://') === 0) {
        $urlWithPrefix = $url;
    } elseif (strpos($url, 'http://') !== 0) {
        $urlWithPrefix = 'http://'.$url;
    }
    
    // ignore tailing special characters
    // TODO: likely this could be skipped entirely with some more tweakes to the regular expression
    if (preg_match("/^(.*)(\.|\,|\?)$/", $urlWithPrefix, $matches)) {
        $urlWithPrefix = $matches[1];
        $url = substr($url, 0, -1);
        $punctuation = $matches[2];
    } else {
        $punctuation = '';
    }
    return '<a href="'.$urlWithPrefix.'" target="_blank">'.$url.'</a>'.$punctuation;
}
```

**Comment by dbu** [comment]
we are not really maintaining this library anymore because nobody at liip is currently using it. it is not up to date with recent symfony versions, not tested on php 7.1 or newer and so on. the travis-ci build fails for the antique php versions and obsolete symfony versions.

in our opinion, the evolution should be to use an existing library for finding urls in text, or splitting out the logic implemented here into a library and have the bundle only integrate the library into symfony.

we archive this bundle now.
