### ISSUE TITLE
Symfony 2.8 conflict

### ISSUE THREAD

**Issue by flierville** [liip/LiipUrlAutoConverterBundle#33]
Hello When I install LiipUrlAutoConverterBundle :
`php composer.phar require liip/url-auto-converter-bundle:dev-master`

I have these errors :

> Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: remove symfony/assetic-bundle v2.8.1
    - Conclusion: don't install symfony/assetic-bundle v2.8.1
    - twig/twig v1.12.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.3 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.14.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.14.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.14.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.15.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.15.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.16.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.16.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.16.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.16.3 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.17.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.18.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.18.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.18.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.19.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.20.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.21.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.21.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.21.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.22.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.22.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.22.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.22.3 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.23.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.23.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.23.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.23.3 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.24.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.24.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.24.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.25.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.26.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.26.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - Installation request for symfony/assetic-bundle (locked at v2.8.1, required as ~2.3) -> satisfiable by symfony/assetic-bundle[v2.8.1].
    - Installation request for liip/url-auto-converter-bundle dev-master -> satisfiable by liip/url-auto-converter-bundle[dev-master].
    - Conclusion: don't install twig/twig v2.2.0|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1
    - Conclusion: remove twig/twig v2.2.0|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1
    - liip/url-auto-converter-bundle dev-master requires twig/twig ~1.12 -> satisfiable by twig/twig[v1.12.0, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0].
    - Can only install one of: twig/twig[v1.27.0, v2.2.0].
    - Can only install one of: twig/twig[v1.28.0, v2.2.0].
    - Can only install one of: twig/twig[v1.28.1, v2.2.0].
    - Can only install one of: twig/twig[v1.28.2, v2.2.0].
    - Can only install one of: twig/twig[v1.29.0, v2.2.0].
    - Can only install one of: twig/twig[v1.30.0, v2.2.0].
    - Can only install one of: twig/twig[v1.31.0, v2.2.0].
    - Can only install one of: twig/twig[v1.32.0, v2.2.0].
    - Installation request for twig/twig (locked at v2.2.0) -> satisfiable by twig/twig[v2.2.0].

**My composer.json :**

> "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/jsrouting-bundle": "^1.5",
        "stof/doctrine-extensions-bundle": "^1.2",
        "twig/extensions": "~1.3",
        "payum/paypal-express-checkout-nvp": "^1.3",
        "php-http/guzzle6-adapter": "^1.1",
        "payum/payum-bundle": "^2.1",
        "payum/offline": "^1.3",
        "stfalcon/tinymce-bundle": "1.0",
        "gregwar/captcha-bundle": "^2.0",
        "friendsofsymfony/rest-bundle": "^2.1",
        "jms-serializer/serializer-bundle": "^1.1",
        "liip/imagine-bundle": "^1.7"

**Comment by dbu** [comment]
maybe its the restriction on the twig version in LiipUrlAutoConverterBundle?

this bundle is not super-deep tied into twig - you could try to allow twig version 2 in the LiipUrlAutoConverterBundle and test if it still works.

**Comment by flierville** [comment]
Thank you, I think it's exactly I need.
But I do not know how to modify the bundle so that it accepts other versions

Could you explain?

**Comment by dbu** [comment]
this explains how you use a fork temporary:

http://tech.osteel.me/posts/2015/08/10/how-to-use-the-fork-of-a-repository-with-composer.html

if the bundle works for you with twig 2, please do a pull request with
the change. once we merge that, you can remove your fork and rely on the
upstream repository again.

**Comment by dbu** [comment]
fixed in #35 and tagged as 1.3.2
